version: '3.9'
services:
  postgis:
    image: postgis/postgis:12-3.1-alpine
    volumes:
      - ./sql/schema:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'

  kosmtik:
    build:
      context: .
      dockerfile: docker/Dockerfile.kosmtik
    volumes:
      - .:/kosmtik
    ports:
      - "127.0.0.1:6789:6789"
    environment:
      - PGHOST=postgis
      - PGUSER=postgres

  mapnik:
    build:
      context: .
      dockerfile: docker/Dockerfile.mapnik
volumes:
  pg_data: {}
