version: '3.9'
services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    environment:
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  mapnik:
    build: .
volumes:
  pg_data: {}
